
spring:  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect          
        

    
item:
 create:
  exception:
     message: Item could not be added
  
