spring:
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect   
  h2:
    console:
      enabled: false

server:
  port: 7072
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
    enabled: true
    fetch-registry: true 
    register-with-eureka: true 
